name: CloudRIG

on: push

jobs:
  build-lib:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Common - Install dependencies
        run: yarn install
      - name: Lib - Build
        run: |
          ls -al
          pwd
          cd lib
          yarn install
          cd ..

  build-cli:
    runs-on: macOS-latest
    needs: build-lib
    steps:
      - name: CLI - Build
        run: |
          ls -al
          pwd
          cd cli
          yarn install

  build-gui:
    runs-on: macOS-latest
    needs: build-lib
    steps:
      - name: GUI - Build
        run: |
          ls -al
          pwd
          cd gui
          yarn install
