name: CloudRIG release

# Only trigger when a release is created
on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Get version
        run: git describe --exact-match --tags $(git log -n1 --pretty='%h')
      - name: Install dependencies
        run: |
          yarn install
          (cd lib && yarn install)
          (cd cli && yarn install)
          (cd gui && yarn install)

